# Generated by Django 5.1.6 on 2025-03-25 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = []
